### ISSUE TITLE
Data not found

### ISSUE THREAD

**Issue by rubensolozabal** [csglab/JAMS#1]
Dear authors, 

Seems that the links you provided to download the data are no longer available.

E.g., not found
wget https://data.cyverse.org/dav-anon/iplant/home/ahcorcha/JAMS_input/GSM2026781_CTCF_rep2.macs.out.txt

Could the data have been relocated elsewhere in cyverse?

Thank you.

**Comment by ahcorcha** [comment]
Dear Ruben,

Thank you for letting us know, I have updated the links (we are now using Galaxy instead of Cyverse) in the file `download_HEK293_CTCF_demo_data.sh`.

The files can also be accessed here: https://usegalaxy.org/u/ahcorcha/h/jamsctcfdemodata

Best,
Aldo

**Comment by rubensolozabal** [comment]
Thank you : )
